import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {AsyncLocalStorage} from 'node:async_hooks';
const require=createRequire(import.meta.url),ts=require('typescript');
function load(name,deps){const code=ts.transpileModule(readFileSync(new URL(name,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,m={exports:{}};Function('require','module','exports',code)(n=>deps[n]??require(n),m,m.exports);return m.exports;}
const env={SIGNAL_IDENTITY_TIMING_DIAGNOSTIC:'isolated-preview-auth-timing-v1',SIGNAL_IDENTITY_OUTBOUND_DIAGNOSTIC:'isolated-preview-clerk-outbound-v1',SIGNAL_SPRINT_PREVIEW_AUTH:'isolated-clerk-preview-v1',SIGNAL_RELIABILITY_ATTEST:'isolated-reliability-v1',SIGNAL_RELIABILITY_ATTEST_UNTIL_MS:String(Date.now()+3600000),VERCEL:'1',VERCEL_ENV:'preview',VERCEL_TARGET_ENV:'preview',NODE_ENV:'production',NEXT_PUBLIC_SIGNAL_DEPLOYMENT_ENV:'preview',SIGNAL_ACCESS_MODE:'production',NEXT_PUBLIC_SIGNAL_ACCESS_MODE:'production',VERCEL_DEPLOYMENT_ID:'dpl_test',VERCEL_PROJECT_ID:'prj_test',VERCEL_URL:'synthetic.vercel.app',NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:'pk_test_synthetic',CLERK_SECRET_KEY:'sk_test_synthetic'};
async function withEnv(values,fn){const keys=[...new Set([...Object.keys(env),'CLERK_API_URL','CLERK_API_VERSION'])],saved=Object.fromEntries(keys.map(k=>[k,process.env[k]]));for(const k of keys)if(values[k]===undefined)delete process.env[k];else process.env[k]=values[k];try{return await fn();}finally{for(const k of keys)if(saved[k]===undefined)delete process.env[k];else process.env[k]=saved[k];}}
function fixture({failClock=false,failLog=false,failSubscribe=false,failStorage=false,failStorageAfter=false}={}){let callback,clocks=0,subscriptions=0;const logs=[];const common={'server-only':{},react:{cache:x=>x},'next/server':{after(){}},'@/lib/auth/recipient-proof-authorized-parties':{SPRINT_PREVIEW_AUTH_MARKER:'isolated-clerk-preview-v1'},'@/server/operational-log':{opLog(){}}};const timing=load('./identity-timing.ts',common);const outbound=load('./identity-outbound.ts',{...common,'@/server/diagnostics/identity-timing':timing});const helper=load('./proxy-timing.ts',{'server-only':{},'node:async_hooks':{AsyncLocalStorage:failStorage?class extends AsyncLocalStorage {run(){throw Error('storage');}}:failStorageAfter?class extends AsyncLocalStorage {run(store,callback){super.run(store,callback);throw Error('storage-after');}}:AsyncLocalStorage},'node:diagnostics_channel':{channel:n=>{assert.equal(n,'undici:request:create');return{subscribe:cb=>{subscriptions++;if(failSubscribe)throw Error('subscription');callback=cb;}};}},'node:perf_hooks':{performance:{now(){clocks++;if(failClock)throw Error('clock');return clocks*10;}}},'@/server/diagnostics/identity-timing':timing,'@/server/diagnostics/identity-outbound':outbound,'@/server/operational-log':{opLog:(a,b,c,d)=>{if(failLog)throw Error('log');logs.push({tag:b,...d});}}});return{helper,logs,publish:e=>callback?.(e),clocks:()=>clocks,subscriptions:()=>subscriptions};}
const req={method:'POST',nextUrl:{pathname:'/api/tasks/mutate'}},event=(path='/v1/jwks')=>({request:{origin:'https://api.clerk.com',method:'GET',path,get headers(){throw Error('private_header');},get body(){throw Error('private_body');}}});
test('disabled and production paths preserve promise identity without clock/subscription/log',()=>withEnv({...env,VERCEL_ENV:'production'},()=>{const f=fixture(),p=Promise.resolve('same');assert.equal(f.helper.withProxyTiming(req,()=>p),p);assert.equal(f.clocks(),0);assert.equal(f.subscriptions(),0);assert.equal(f.logs.length,0);}));
test('other routes and missing flags direct passthrough',()=>withEnv({...env,SIGNAL_IDENTITY_OUTBOUND_DIAGNOSTIC:undefined},()=>{const f=fixture(),p=Promise.resolve(1);assert.equal(f.helper.withProxyTiming(req,()=>p),p);assert.equal(f.helper.withProxyTiming({...req,method:'GET'},()=>p),p);assert.equal(f.clocks(),0);}));
test('enabled returns exact response; fixed header and numeric privacy counters',()=>withEnv(env,async()=>{const f=fixture(),response={headers:new Headers()};assert.equal(await f.helper.withProxyTiming(req,()=>{f.publish(event());f.publish(event('/v1/users/private-canary'));return response;}),response);assert.equal(response.headers.get('server-timing'),'signalProxy;dur=10');assert.equal(f.logs[0].jwksAttempts,1);assert.equal(f.logs[0].otherAttempts,1);assert.equal(f.logs[0].transportObserved,true);assert(!JSON.stringify(f.logs).includes('private-canary'));}));
test('original rejection retained; clock/log/header diagnostic failures never replay',()=>withEnv(env,async()=>{const f=fixture({failLog:true}),error=Error('original');let calls=0;await assert.rejects(f.helper.withProxyTiming(req,()=>{calls++;throw error;}),e=>e===error);assert.equal(calls,1);const clock=fixture({failClock:true});assert.equal(clock.helper.withProxyTiming(req,()=>{calls++;return 42;}),42);assert.equal(calls,2);}));
test('concurrent ALS scopes remain independent',()=>withEnv(env,async()=>{const f=fixture();let release;const wait=new Promise(r=>release=r);const a=f.helper.withProxyTiming(req,async()=>{await wait;f.publish(event());return 'a';});const b=f.helper.withProxyTiming(req,async()=>{f.publish(event('/other'));return 'b';});assert.equal(await b,'b');release();assert.equal(await a,'a');assert.deepEqual(f.logs.map(x=>[x.jwksAttempts,x.otherAttempts]),[[0,1],[1,0]]);}));
test('subscription/malformed/overflow explicitly incomplete and bounded',()=>withEnv(env,async()=>{const f=fixture();await f.helper.withProxyTiming(req,()=>{f.publish({request:{}});for(let i=0;i<40;i++)f.publish(event());return {};});assert.equal(f.logs[0].incomplete,true);assert.equal(f.logs[0].jwksAttempts,31);const no=fixture({failSubscribe:true});await no.helper.withProxyTiming(req,()=>({}));assert.equal(no.logs[0].transportObserved,false);assert.equal(no.logs[0].incomplete,true);}));
test('real strict guards reject unrelated/expired/live-key environments',()=>withEnv({...env,CLERK_SECRET_KEY:'sk_live_canary'},()=>{const f=fixture(),p=Promise.resolve(1);assert.equal(f.helper.withProxyTiming(req,()=>p),p);assert.equal(f.clocks(),0);}));

test('route span preserves response, refusal and original error without transport subscription',()=>withEnv(env,async()=>{const f=fixture(),response={headers:new Headers()};assert.equal(await f.helper.withRouteTiming(()=>response),response);assert.equal(response.headers.get('server-timing'),'signalRoute;dur=10');assert.equal(f.subscriptions(),0);const error=Error('route-original');await assert.rejects(f.helper.withRouteTiming(()=>{throw error;}),e=>e===error);const immutable={get headers(){throw Error('immutable');}};assert.equal(await f.helper.withRouteTiming(()=>immutable),immutable);}));
test('route disabled retains promise identity and expired guards do not start clocks',()=>withEnv({...env,SIGNAL_RELIABILITY_ATTEST_UNTIL_MS:'1'},()=>{const f=fixture(),p=Promise.resolve(1);assert.equal(f.helper.withRouteTiming(()=>p),p);assert.equal(f.helper.withProxyTiming(req,()=>p),p);assert.equal(f.clocks(),0);assert.equal(f.subscriptions(),0);}));
test('proxy immutable headers do not change outcome and no observed events remain unknown',()=>withEnv(env,async()=>{const f=fixture(),response={get headers(){throw Error('immutable');}};assert.equal(await f.helper.withProxyTiming(req,()=>response),response);assert.equal(f.logs[0].transportObserved,false);assert.equal(f.logs[0].incomplete,true);}));

test('ALS setup failure falls back exactly once without instrumentation',()=>withEnv(env,()=>{const f=fixture({failStorage:true}),p=Promise.resolve('original');let calls=0;assert.equal(f.helper.withProxyTiming(req,()=>{calls++;return p;}),p);assert.equal(calls,1);assert.equal(f.logs.length,0);}));

test('ALS failure after callback never replays original success or rejection',()=>withEnv(env,async()=>{for(const rejects of [false,true]){const f=fixture({failStorageAfter:true}),error=Error('original-after');let calls=0;const result=f.helper.withProxyTiming(req,()=>{calls++;if(rejects)throw error;return 'original';});if(rejects)await assert.rejects(result,e=>e===error);else assert.equal(await result,'original');assert.equal(calls,1);assert.equal(f.logs[0].incomplete,true);}}));
