import { chromium } from "@playwright/test";
const base = "file:///C:/Users/ethan/signal-studio-workspace/_wt-design-notes/docs/design/labs/notes-2026-08/notebook.html";
const out = "C:/Users/ethan/signal-studio-workspace/_wt-design-notes/_seat/ux4/";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 960 }, deviceScaleFactor:2 });
await p.goto(base + "?state=review"); await p.waitForTimeout(400);
await p.keyboard.press("t"); await p.waitForTimeout(700);
console.log("handBody html:", (await p.evaluate(()=>document.querySelector('.handBody')?.outerHTML||'none')).replace(/\s+/g,' ').slice(0,600));
console.log("peel picked:", await p.evaluate(()=>document.querySelector('.peel .picked, .peel [class*=pick]')?.textContent||'?'));
const bb = await p.evaluate(()=>{const n=document.querySelector('.hand');const r=n.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}});
await p.screenshot({path:out+"hand-peel.png", clip:{x:bb.x-10,y:bb.y-10,width:bb.w+20,height:Math.min(bb.h+20, 960-bb.y)}});
await b.close();
