import { chromium } from "@playwright/test";
const base = "file:///C:/Users/ethan/signal-studio-workspace/_wt-design-notes/docs/design/labs/notes-2026-08/notebook.html";
const out = "C:/Users/ethan/signal-studio-workspace/_wt-design-notes/_seat/ux4/";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 960 } });
p.on("console", m=>{ if(m.type()==="error") console.log("CONSOLE ERR: "+m.text()); });
await p.goto(base + "?state=notebook");
await p.waitForTimeout(500);
console.log("focus at rest:", await p.evaluate(()=>{const a=document.activeElement;return a.tagName+" "+(a.getAttribute("aria-label")||a.className||"")}));
console.log("live regions:", JSON.stringify(await p.evaluate(()=>[...document.querySelectorAll('[aria-live],[role=status],[role=alert]')].map(n=>({r:n.getAttribute('role'),l:n.getAttribute('aria-live'),cls:n.className,txt:(n.textContent||'').slice(0,80)})))));
const t0 = Date.now();
await p.keyboard.type("Ring the florist about the arch");
console.log("type ms", Date.now()-t0);
await p.waitForTimeout(300);
console.log("live after typing:", JSON.stringify(await p.evaluate(()=>[...document.querySelectorAll('[aria-live]')].map(n=>(n.textContent||'').slice(0,120)))));
await p.screenshot({path:out+"s-typed.png"});
const t1 = Date.now();
await p.keyboard.press("Control+Enter");
await p.waitForTimeout(1400);
console.log("commit->settle ms", Date.now()-t1);
console.log("live after keep:", JSON.stringify(await p.evaluate(()=>[...document.querySelectorAll('[aria-live]')].map(n=>(n.textContent||'').slice(0,200)))));
console.log("focus after keep:", await p.evaluate(()=>{const a=document.activeElement;return a.tagName+" "+(a.getAttribute("aria-label")||a.className||"")}));
await p.screenshot({path:out+"s-kept.png"});
console.log("header:", await p.evaluate(()=>document.querySelector('header')?.innerText.replace(/\n/g,' | ')));
console.log("full text:", (await p.evaluate(()=>document.body.innerText)).slice(0,2500));
await b.close();
