import { chromium } from "@playwright/test";
import fs from "fs";
const BASE = "file:///C:/Users/ethan/signal-studio-workspace/_wt-design-notes/docs/design/labs/notes-2026-08/notebook.html";
const OUT = "C:/Users/ethan/signal-studio-workspace/_wt-design-notes/_shots";
fs.mkdirSync(OUT, { recursive: true });
const lines = [];
const log = (...a) => { lines.push(a.join(" ")); fs.writeFileSync(OUT + "/log.txt", lines.join("\n")); };
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 960 } });
await p.goto(BASE + "?state=notebook");
await p.waitForTimeout(600);
log("LOADED");
await p.click(".topField");
await p.type(".topField", "Ring the florist about Saturday delivery", { delay: 8 });
log("foot:", (await p.locator(".topFoot").innerText()).replace(/\n/g," | "));
await p.keyboard.press("Control+Enter");
await p.waitForTimeout(350);
log("SAY:", await p.locator("#say").innerText());
log("UNDO:", (await p.locator(".undo").innerText()).replace(/\n/g," | "));
log("CHIP:", await p.locator(".chip").innerText());
log("IDXHEAD:", (await p.locator(".indexHead").first().innerText()).replace(/\n/g," | "));
await p.keyboard.press("Control+z");
await p.waitForTimeout(250);
log("SAY after undo:", await p.locator("#say").innerText());
log("field after undo:", JSON.stringify(await p.locator(".topField").inputValue()));
await b.close();
log("DONE");
