#!/usr/bin/env node

/**
 * Generates the static QR matrix behind the Signal Studio QR mark.
 *
 * The mark is rendered as SVG at runtime (src/components/brand/signal-qr.tsx)
 * so it inherits the surface's ink colour and needs no image request. Only the
 * module matrix is generated here, and it is committed, so the app has no
 * build-time or runtime dependency on the qrcode package.
 *
 * Error correction is HIGH: the mark carries a centre badge and rounded
 * modules, both of which eat into the readable area.
 *
 *   node scripts/brand/generate-qr.mjs
 *
 * Change TARGET when the iPhone app has an App Store listing, then re-run.
 * It aimed at the umbrella `/ios` page until the 2026-08-12 estate
 * consolidation retired that page. A QR is printed and scanned months after
 * it ships, so it encodes a live URL, never one that redirects.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import QRCode from "qrcode";

const TARGET = "https://signalstudio.ie/";
const OUT = path.join(
  process.cwd(),
  "src",
  "components",
  "brand",
  "qr-matrix.generated.ts",
);

const qr = QRCode.create(TARGET, { errorCorrectionLevel: "H" });
const size = qr.modules.size;
const rows = [];

for (let row = 0; row < size; row += 1) {
  let line = "";
  for (let col = 0; col < size; col += 1) {
    line += qr.modules.get(row, col) ? "1" : "0";
  }
  rows.push(line);
}

const file = `// GENERATED by scripts/brand/generate-qr.mjs — do not edit by hand.
// Target: ${TARGET}
// Error correction: H (30%). Version ${(size - 17) / 4}, ${size}×${size} modules.

export const QR_TARGET = ${JSON.stringify(TARGET)};

export const QR_SIZE = ${size};

/** One string per row. "1" is a dark module. */
export const QR_ROWS: readonly string[] = [
${rows.map((line) => `  ${JSON.stringify(line)},`).join("\n")}
];
`;

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, file, "utf8");

console.log(`Wrote ${path.relative(process.cwd(), OUT)} (${size}x${size})`);
