import "server-only";

import { createHash } from "node:crypto";
import type { Client } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import { normalizePingCommand, normalizePingCommandId, pingProofDueAtSeconds, validPingId,
  type PingCommand, type PingTaskPrecondition } from "@/lib/ping/command";
import { parseColumnConfig } from "@/lib/board-config";
import { isTaskDone, isDoneColumnKey } from "@/lib/board-columns";
import { projectCapabilities, resolveProjectRole } from "@/server/projects/capabilities";
import { createTaskInTransaction, prepareCanonicalTaskCreate } from "@/server/tasks/create-task-core";
import { conversationWriteFencesClear } from "@/server/conversations/write-fences";
import type { ConversationDatabaseAdapter, ConversationSqlExecutor, ConversationSqlValue } from "@/server/conversations/database";
import { captureTaskCreated, type CaptureConfig } from "@/server/sponsored-use/capture";
import * as schema from "@/server/db/schema";

/** Trusted transport/capture boundary, never generated by an interpreter or accepted as model fields. */
export type PingExecutionContext = Readonly<{
  actorId: string;
  captured: Readonly<{ commandId: string; projectId: string; selectedTaskIds: readonly string[];
    referenceInstant: string; timeZone: "Europe/Dublin"; expectedColumnConfig: string | null;
    inputItemId: string; expected: Readonly<Record<string, PingTaskPrecondition>> }>;
  input: Readonly<{ itemId: string; state: "complete" | "incomplete" }>;
}>;
export type PingReceipt = Readonly<{
  version: "ping.receipt.v1"; commandId: string; projectId: string; committedAtSeconds: number;
  outcome: "completed" | "no_changes"; affectedCount: number; changedCount: number;
  effects: readonly Readonly<{ taskId: string; changedFields: readonly string[]; seq?: number }>[];
}>;
export type PingFailureReason = "invalid_command" | "incomplete_input" | "unavailable" | "conflict" |
  "request_conflict" | "temporarily_unavailable";
export type PingExecutionResult = Readonly<{ ok: true; receipt: PingReceipt; replayed: boolean }> |
  Readonly<{ ok: false; reason: PingFailureReason }>;
export type PingReceiptLookup = Readonly<{ ok: true; state: "absent" }> |
  Readonly<{ ok: true; state: "committed"; receipt: PingReceipt }> |
  Readonly<{ ok: false; reason: "unavailable" | "invalid_command" | "temporarily_unavailable" }>;
export type PingBoundReceiptLookup = Exclude<PingReceiptLookup, { ok: false }> |
  Readonly<{ ok: false; reason: PingFailureReason }>;
export type PingProofSeam = "task" | "activity" | "capture" | "receipt";

const fail = (reason: PingFailureReason): Extract<PingExecutionResult, { ok: false }> => ({ ok: false, reason });
function stable(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`;
  if (value !== null && typeof value === "object") return `{${Object.keys(value).sort()
    .map((key) => `${JSON.stringify(key)}:${stable((value as Record<string, unknown>)[key])}`).join(",")}}`;
  return JSON.stringify(value);
}
function hash(value: unknown): string { return createHash("sha256").update(stable(value)).digest("hex"); }
function nullable(value: unknown): number | null { return value == null ? null : Number(value); }

function capturedContextMatches(command: PingCommand, context: PingExecutionContext): boolean {
  const captured = context.captured;
  if (!validPingId(context.actorId) || !captured || !context.input ||
    !validPingId(captured.inputItemId) || context.input.itemId !== captured.inputItemId ||
    normalizePingCommandId(captured.commandId) !== command.commandId || captured.projectId !== command.projectId ||
    captured.referenceInstant !== command.referenceInstant || captured.timeZone !== command.timeZone ||
    captured.expectedColumnConfig !== command.expectedColumnConfig || !Array.isArray(captured.selectedTaskIds) ||
    captured.selectedTaskIds.length > 10 || !captured.selectedTaskIds.every(validPingId) ||
    new Set(captured.selectedTaskIds).size !== captured.selectedTaskIds.length) return false;
  if (command.operation.kind === "create_placeholders") return true;
  if (stable([...captured.selectedTaskIds].sort()) !== stable(command.operation.taskIds)) return false;
  for (const taskId of command.operation.taskIds) {
    const authoritative = captured.expected?.[taskId];
    if (!authoritative) return false;
    for (const [field, expected] of Object.entries(command.operation.expected[taskId])) {
      const actual = authoritative[field as keyof PingTaskPrecondition];
      if (field === "assignees") {
        if (!Array.isArray(actual) || stable([...actual].sort()) !== stable(expected)) return false;
      } else if (actual !== expected) return false;
    }
  }
  return true;
}

/** Separate fresh membership-rooted authorization statement; canonical capability model decides. */
async function authorized(tx: ConversationSqlExecutor, actorId: string, projectId: string, writing: boolean): Promise<boolean> {
  const result = await tx.execute({ sql: `SELECT member.role AS role, project.owner_user_id AS owner_id,
      project.archived_at AS archived_at
    FROM workspace_members member JOIN workspaces project ON project.id = member.workspace_id
    WHERE member.user_id = ? AND member.workspace_id = ? LIMIT 1`, args: [actorId, projectId] });
  const row = result.rows[0];
  if (!row || (row.role !== "owner" && row.role !== "member")) return false;
  const role = resolveProjectRole({ actorUserId: actorId,
    membershipRole: row.role === "owner" ? "owner" : "member",
    workspaceOwnerUserId: row.owner_id == null ? null : String(row.owner_id) });
  const capabilities = projectCapabilities({ role, archived: row.archived_at != null, ownsPlanningPeriod: false });
  if (!(writing ? capabilities.createOrEditTasks : capabilities.open)) return false;
  return conversationWriteFencesClear(tx, actorId, projectId);
}

async function storedReceipt(tx: ConversationSqlExecutor, actorId: string, commandId: string) {
  return (await tx.execute({ sql: `SELECT project_id, plan_hash, receipt_json FROM ping_command_receipts
    WHERE actor_id = ? AND command_id = ?`, args: [actorId, commandId] })).rows[0];
}

type TaskRow = Record<string, unknown>;
function satisfies(row: TaskRow, expected: PingTaskPrecondition): boolean {
  for (const [field, value] of Object.entries(expected)) {
    const actual = field === "assignees" ? JSON.parse(String(row.assignees)) :
      field === "dueAtSeconds" ? nullable(row.due_at) : field === "startDay" ? nullable(row.start_day) :
      field === "durationDays" ? nullable(row.duration_days) : field === "boardColumnKey" ? row.board_column_key ?? null :
      field === "completedAtSeconds" ? nullable(row.completed_at) : row[field] ?? null;
    if (field === "assignees") {
      if (!Array.isArray(actual) || stable([...actual].sort()) !== stable(value)) return false;
    } else if (actual !== value) return false;
  }
  return true;
}

/** Private injected service only: no app route, environment loading, DB singleton or interpreter authority. */
export function createPingCommandService(adapter: ConversationDatabaseAdapter, options: Readonly<{
  now?: () => number;
  captureConfig?: CaptureConfig;
  afterWrite?: (seam: PingProofSeam, taskIndex: number) => void | Promise<void>;
}> = {}) {
  const now = options.now ?? Date.now;

  async function execute(args: Readonly<{ command: unknown; context: PingExecutionContext }>): Promise<PingExecutionResult> {
    const normalized = normalizePingCommand(args.command);
    if (!normalized.ok) return fail("invalid_command");
    let context: PingExecutionContext;
    try { context = structuredClone(args.context); } catch { return fail("invalid_command"); }
    const command = normalized.value;
    if (!context || !capturedContextMatches(command, context)) return fail("invalid_command");
    if (context.input.state !== "complete") return fail("incomplete_input");
    if (!adapter.available) return fail("temporarily_unavailable");
    const actorId = context.actorId;
    const planHash = hash({ actorId, command, captured: { ...context.captured, commandId: command.commandId } });
    try {
      // Receipt recovery is read-only. Do not require a fresh writer lock to disclose a committed result.
      // Absence is only a hint: the write transaction repeats this lookup to close concurrent first-write races.
      const recovered = await adapter.transaction("read", async (tx): Promise<PingExecutionResult | null> => {
        const previous = await storedReceipt(tx, actorId, command.commandId);
        if (!previous) return null;
        if (!await authorized(tx, actorId, String(previous.project_id), false)) return fail("unavailable");
        if (previous.plan_hash !== planHash) return fail("request_conflict");
        return { ok: true, receipt: JSON.parse(String(previous.receipt_json)) as PingReceipt, replayed: true };
      });
      if (recovered) return recovered;
      return await adapter.transaction("write", async (tx): Promise<PingExecutionResult> => {
        const previous = await storedReceipt(tx, actorId, command.commandId);
        if (previous) {
          if (!await authorized(tx, actorId, String(previous.project_id), false)) return fail("unavailable");
          if (previous.plan_hash !== planHash) return fail("request_conflict");
          return { ok: true, receipt: JSON.parse(String(previous.receipt_json)) as PingReceipt, replayed: true };
        }
        if (!await authorized(tx, actorId, command.projectId, true)) return fail("unavailable");
        const configResult = await tx.execute({ sql: "SELECT value FROM meta WHERE key = ?",
          args: [`board:${command.projectId}:columns`] });
        const rawConfig = configResult.rows[0]?.value == null ? null : String(configResult.rows[0].value);
        const effect = command.operation.effects;
        if ((command.operation.kind === "create_placeholders" || effect.statusColumnKey) &&
          rawConfig !== command.expectedColumnConfig) return fail("conflict");
        const config = rawConfig == null ? null : parseColumnConfig(rawConfig);
        const committedAtSeconds = Math.floor(now() / 1000);
        const results: Array<{ taskId: string; changedFields: string[]; seq?: number }> = [];

        if (command.operation.kind === "edit_selected") {
          const rows: TaskRow[] = [];
          for (const taskId of command.operation.taskIds) {
            const row = (await tx.execute({ sql: "SELECT * FROM tasks WHERE id = ? AND workspace_id = ?",
              args: [taskId, command.projectId] })).rows[0];
            if (!row || row.archived_at != null || row.parent_task_id != null || row.recurrence != null ||
              Number(row.is_milestone ?? 0) !== 0 || row.board_column_key != null ||
              !satisfies(row, command.operation.expected[taskId])) return fail("conflict");
            rows.push(row);
          }
          for (let index = 0; index < rows.length; index++) {
            const row = rows[index];
            const patch: Record<string, ConversationSqlValue> = {};
            const changedFields: string[] = [];
            if (effect.selfAssignment) {
              const prior = JSON.parse(String(row.assignees)) as string[];
              const next = effect.selfAssignment === "add" ? (prior.includes(actorId) ? prior : [...prior, actorId]) :
                prior.filter((id) => id !== actorId);
              if (stable(prior) !== stable(next)) { patch.assignees = JSON.stringify(next); changedFields.push("assignees"); }
            }
            if (Object.hasOwn(effect, "dueDate")) {
              const dueDate = effect.dueDate ?? null;
              const dueAt = pingProofDueAtSeconds(dueDate);
              if ((row.due ?? null) !== dueDate || nullable(row.due_at) !== dueAt) {
                patch.due = dueDate; patch.due_at = dueAt; changedFields.push("due");
              }
            }
            if (effect.statusColumnKey && row.lane !== effect.statusColumnKey) {
              patch.lane = effect.statusColumnKey; patch.board_column_key = null; patch.idle_days = null;
              const wasDone = isTaskDone({ lane: String(row.lane), boardColumnKey: null }, config);
              const doneNow = isDoneColumnKey(effect.statusColumnKey, config);
              if (wasDone !== doneNow) patch.completed_at = doneNow ? committedAtSeconds : null;
              changedFields.push("lane");
            }
            if (changedFields.length) {
              patch.updated_at = committedAtSeconds;
              const keys = Object.keys(patch); // Every column is application-owned above, never taken from input.
              await tx.execute({ sql: `UPDATE tasks SET ${keys.map((key) => `${key} = ?`).join(", ")}
                WHERE id = ? AND workspace_id = ?`, args: [...keys.map((key) => patch[key]), String(row.id), command.projectId] });
              await options.afterWrite?.("task", index + 1);
              for (const field of changedFields) {
                await tx.execute({ sql: `INSERT INTO activities(id,workspace_id,task_id,user_id,kind,payload,created_at)
                  VALUES (?,?,?,?, 'update', ?,?)`, args: [`ping-a-${hash([actorId, command.commandId, row.id, field]).slice(0, 24)}`,
                    command.projectId, String(row.id), actorId, JSON.stringify({ kind: "update", field }), committedAtSeconds] });
                await options.afterWrite?.("activity", index + 1);
              }
            }
            results.push({ taskId: String(row.id), changedFields });
          }
        } else {
          const { count, title } = command.operation;
          const lane = effect.statusColumnKey ?? "todo";
          for (let index = 0; index < count; index++) {
            const id = `ping-t-${hash([actorId, command.commandId, index]).slice(0, 24)}`;
            const dueDate = effect.dueDate ?? null;
            const task = prepareCanonicalTaskCreate({ id, workspaceId: command.projectId, title, lane,
              assignees: effect.selfAssignment === "add" ? [actorId] : [], due: dueDate,
              dueAt: dueDate == null ? null : new Date(pingProofDueAtSeconds(dueDate)! * 1000),
              completedAt: isDoneColumnKey(lane, config) ? new Date(committedAtSeconds * 1000) : null,
              createdAt: new Date(committedAtSeconds * 1000) });
            const created = await createTaskInTransaction({
              async nextPosition(value) {
                const result = await tx.execute({ sql: "SELECT COALESCE(MAX(position),0)+1 AS position FROM tasks WHERE workspace_id=? AND lane=?",
                  args: [value.workspaceId, value.lane] });
                return Number(result.rows[0]?.position ?? 1);
              },
              async insertTask(value) {
                const result = await tx.execute({ sql: `INSERT INTO tasks(id,workspace_id,seq,title,description,lane,priority,assignees,
                  due,due_at,estimate,tags,recurrence,position,parent_task_id,completed_at,is_milestone,created_at,updated_at)
                  VALUES (?,?,(SELECT COALESCE(MAX(seq),0)+1 FROM tasks WHERE workspace_id=?),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING seq`,
                  args: [value.id, value.workspaceId, value.workspaceId, value.title, value.description, value.lane, value.priority,
                    JSON.stringify(value.assignees), value.due, value.dueAtSeconds, value.estimate, value.tags == null ? null : JSON.stringify(value.tags),
                    value.recurrence == null ? null : JSON.stringify(value.recurrence), value.position, value.parentTaskId,
                    value.completedAtSeconds, value.isMilestone ? 1 : 0, value.createdAtSeconds, value.createdAtSeconds] });
                await options.afterWrite?.("task", index + 1);
                return { seq: Number(result.rows[0]?.seq) };
              },
              async insertActivity(value) {
                await tx.execute({ sql: `INSERT INTO activities(id,workspace_id,task_id,user_id,kind,payload,created_at)
                  VALUES (?,?,?,?, 'taskAdd', ?,?)`, args: [`ping-a-${hash([value.id, "taskAdd"]).slice(0, 24)}`,
                    value.workspaceId, value.id, actorId, JSON.stringify({ kind: "taskAdd", lane: value.lane }), value.createdAtSeconds] });
                await options.afterWrite?.("activity", index + 1);
              },
            }, task);
            // Explicit configuration: never reads ambient sponsor settings or emits network delivery.
            await captureTaskCreated(drizzle(tx as unknown as Client, { schema }), { actorUserId: actorId,
              projectId: command.projectId }, options.captureConfig ?? { enabled: false, now: committedAtSeconds * 1000 });
            await options.afterWrite?.("capture", index + 1);
            results.push({ taskId: created.taskId, changedFields: ["created"], seq: created.seq });
          }
        }
        const changedCount = results.filter((value) => value.changedFields.length > 0).length;
        const receipt: PingReceipt = { version: "ping.receipt.v1", commandId: command.commandId,
          projectId: command.projectId, committedAtSeconds, outcome: changedCount ? "completed" : "no_changes",
          affectedCount: results.length, changedCount, effects: results };
        await tx.execute({ sql: `INSERT INTO ping_command_receipts(actor_id,command_id,project_id,plan_hash,receipt_json,committed_at)
          VALUES (?,?,?,?,?,?)`, args: [actorId, command.commandId, command.projectId, planHash, JSON.stringify(receipt), committedAtSeconds] });
        await options.afterWrite?.("receipt", results.length);
        return { ok: true, receipt, replayed: false };
      });
    } catch { return fail("temporarily_unavailable"); } // Never serialize driver errors containing bound private text.
  }

  async function getReceipt(args: Readonly<{ actorId: string; commandId: string }>): Promise<PingReceiptLookup> {
    const commandId = normalizePingCommandId(args.commandId);
    if (!validPingId(args.actorId) || commandId === null) {
      return { ok: false, reason: "invalid_command" };
    }
    if (!adapter.available) return { ok: false, reason: "temporarily_unavailable" };
    try {
      return await adapter.transaction("read", async (tx): Promise<PingReceiptLookup> => {
        const receipt = await storedReceipt(tx, args.actorId, commandId);
        if (!receipt) return { ok: true, state: "absent" };
        if (!await authorized(tx, args.actorId, String(receipt.project_id), false)) return { ok: false, reason: "unavailable" };
        return { ok: true, state: "committed", receipt: JSON.parse(String(receipt.receipt_json)) as PingReceipt };
      });
    } catch { return { ok: false, reason: "temporarily_unavailable" }; }
  }
  /** Read-only original-intent recovery. Absence never delegates permission to retry a mutation. */
  async function getReceiptForCommand(args: Readonly<{ command: unknown; context: PingExecutionContext }>): Promise<PingBoundReceiptLookup> {
    try {
      const normalized = normalizePingCommand(args.command);
      if (!normalized.ok) return fail("invalid_command");
      const context: PingExecutionContext = structuredClone(args.context);
      const command = normalized.value;
      if (!context || !capturedContextMatches(command, context)) return fail("invalid_command");
      if (context.input.state !== "complete") return fail("incomplete_input");
      if (!adapter.available) return fail("temporarily_unavailable");
      const actorId = context.actorId;
      const planHash = hash({ actorId, command, captured: { ...context.captured, commandId: command.commandId } });
      return await adapter.transaction("read", async (tx): Promise<PingBoundReceiptLookup> => {
        // Fresh authority also applies to an absent read; no arbitrary Project probing through this seam.
        if (!await authorized(tx, actorId, command.projectId, false)) return fail("unavailable");
        const previous = await storedReceipt(tx, actorId, command.commandId);
        if (!previous) return { ok: true, state: "absent" };
        if (previous.project_id !== command.projectId || previous.plan_hash !== planHash) return fail("request_conflict");
        const receipt = JSON.parse(String(previous.receipt_json)) as PingReceipt;
        if (receipt.commandId !== command.commandId || receipt.projectId !== command.projectId) return fail("request_conflict");
        return { ok: true, state: "committed", receipt };
      });
    } catch { return fail("temporarily_unavailable"); }
  }
  return { execute, getReceipt, getReceiptForCommand };
}
