import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
const [scratch,label,portText]=process.argv.slice(2),origin='http://127.0.0.1:'+Number(portText),out=path.join(scratch,label);
if(fs.existsSync(out))throw Error('Never overwrite');fs.mkdirSync(out);
const load=createRequire('C:/Users/ethan/signal-studio-workspace/worktrees/app/feat-january-final-journeys/package.json');
const mod=await import(pathToFileURL(load.resolve('@playwright/test')).href),{chromium,expect}=mod.default||mod;
const data=JSON.parse(fs.readFileSync(path.join(scratch,'states.json'))),receipt={source:data.source,cases:[],screenshots:[],errors:[],external:[]};
const browser=await chromium.launch({headless:true});
async function run(width,theme,names,interaction=false){
 const context=await browser.newContext({viewport:{width,height:width===390?844:1000},locale:'en-GB',timezoneId:'Europe/Dublin',colorScheme:theme,reducedMotion:'reduce'});
 await context.route('**/*',r=>{if(new URL(r.request().url()).origin!==origin){receipt.external.push(r.request().url());return r.abort()}return r.continue()});
 const page=await context.newPage();let active;
 page.on('pageerror',e=>receipt.errors.push({case:active,error:String(e)}));page.on('console',m=>{if(['error','warning'].includes(m.type()))receipt.errors.push({case:active,type:m.type(),text:m.text()})});page.on('response',r=>{if(r.status()>=400)receipt.errors.push({case:active,status:r.status(),url:r.url()})});
 const notice=page.getByRole('status',{name:'Pending access removal'});
 async function view(name){await page.goto(origin+'/?state='+name+'&theme='+theme);await page.locator('main').waitFor();if(!['member','flag-off'].includes(name))await page.getByRole('heading',{name:'A home for this board’s files'}).waitFor();}
 async function check(name){const expected=data.cases.find(c=>c.name===name);await expect(notice).toHaveCount(expected.current+expected.previous>0?1:0);if(expected.current)await expect(notice).toContainText('current Drive folder');else await expect(notice.filter({hasText:'current Drive folder'})).toHaveCount(0);if(expected.previous)await expect(notice).toContainText('previous Drive folders');else await expect(notice.filter({hasText:'previous Drive folders'})).toHaveCount(0);const text=await page.locator('main').innerText();if(/private-permission|stale-private|live-private|Private provider|conn-old|gen-current/.test(text))throw Error('Private identity/receipt leaked');if(name.startsWith('unavailable')||name==='appears-during-failed-live-read'){await expect(page.getByText(/No current permissions are confirmed here/)).toBeVisible();await expect(page.getByText('Can edit',{exact:true})).toHaveCount(0);}if(['current','previous','both','cleared-during-live-read'].includes(name))await expect(page.getByText('Can edit',{exact:true})).toBeVisible();}
 async function shot(name){await page.evaluate(()=>document.fonts.ready);const metrics=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,font:getComputedStyle(document.body).fontFamily,theme:document.documentElement.dataset.theme,background:getComputedStyle(document.body).backgroundColor,focus:{tag:document.activeElement.tagName,outline:getComputedStyle(document.activeElement).outlineStyle}}));if(metrics.scrollWidth>width+1)throw Error('Horizontal overflow');const file=name+'-'+width+'-'+theme+'.png';await page.screenshot({path:path.join(out,file),fullPage:true});receipt.screenshots.push({case:active,file,metrics});}
 async function test(name,fn){active=name+'-'+width+'-'+theme;const record={name,width,theme,ok:false};try{await fn(record);record.ok=true}catch(e){record.error=String(e);await page.screenshot({path:path.join(out,'failure-'+active+'.png'),fullPage:true}).catch(()=>{})}receipt.cases.push(record);}
 for(const name of names)await test(name,async record=>{await view(name);await check(name);await page.reload();await page.getByRole('heading',{name:'A home for this board’s files'}).waitFor();await check(name);record.remounted=true;record.reads=await page.evaluate(()=>window.__removal.reads);await shot(name);});
 if(interaction){
  await test('keyboard-refresh-pending-unavailable-clear',async record=>{await view('current');await check('current');for(const state of ['unavailable-both','cleared-during-live-read','current']){await page.evaluate(s=>{window.__removal.state=s},state);const button=page.getByRole('button',{name:'Check again',exact:true});await button.focus();await page.keyboard.press('Enter');await page.getByRole('heading',{name:'A home for this board’s files'}).waitFor();await check(state);await shot('refresh-'+state);}record.reads=await page.evaluate(()=>window.__removal.reads);if(record.reads.length!==4)throw Error('Unexpected action-read count');});
  await test('member-and-flag-off',async record=>{for(const state of ['member','flag-off']){await view(state);await expect(notice).toHaveCount(0);await expect(page.getByRole('button',{name:/Connect|Disconnect|Check again/})).toHaveCount(0);const reads=await page.evaluate(()=>window.__removal.reads);if(reads.length)throw Error('Disallowed component dispatched management read');await shot(state);}record.managementReads=0;});
 }
 await context.close();
}
try{
 for(const width of [390,1440])await run(width,'light',data.cases.map(c=>c.name),true);
 for(const width of [390,1440])await run(width,'dark',['current','previous','unavailable-both']);
 await run(768,'light',['both','previous-no-current']);await run(1920,'light',['both','unavailable-both']);
}finally{await browser.close();receipt.pass=receipt.cases.filter(c=>c.ok).length;receipt.fail=receipt.cases.length-receipt.pass;receipt.completedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'receipt.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({pass:receipt.pass,fail:receipt.fail,screenshots:receipt.screenshots.length,errors:receipt.errors.length,external:receipt.external.length}));process.exitCode=receipt.fail||receipt.errors.length||receipt.external.length?1:0;}
