/**
 * Home fixture universe · the evidence manifest.
 *
 * Writes `experience/home-operating-layer/fixtures/manifest.json` — one file
 * a reviewer can diff to see whether a change moved a number, and which one.
 *
 * WHY A FILE AND NOT A REPORT. The fixture's numbers are derived, so they can
 * change silently when a record changes. A committed manifest turns that into
 * a visible diff in a pull request: "the fixture now says 6 capped, it said 2"
 * is a review conversation, and a number nobody wrote down is not.
 *
 * Run:
 *   node --import tsx src/lib/home-layer/fixtures/emit-manifest.ts
 *
 * This module is NOT exported from `./index.ts`: it touches the filesystem,
 * and the lab's transitive-import gate must never see `node:fs` in the
 * family the lab consumes.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import {
  HOME_FIXTURE_DST,
  HOME_FIXTURE_LOCALE,
  HOME_FIXTURE_NOW_ISO,
  HOME_FIXTURE_TIME_ZONE,
  HOME_FIXTURE_TODAY,
} from "./clock";
import { MAX_EXCEPTIONS, TREND_MINIMUM_SNAPSHOTS, WITHHELD_CLAIMS } from "./analytics";
import { HOME_INBOX_SNOOZE_CASES } from "./inbox";
import { MY_WORK_COVERAGE_RECEIPT, MY_WORK_WINDOW } from "./my-work";
import {
  NOTE_BODY_SENTINEL_PREFIX,
  NOTE_EXTRACT_SENTINEL_PREFIX,
  HOME_FIXTURE_NOTES,
} from "./notes";
import { HOME_FIXTURE_ALL_PROJECTS } from "./projects";
import {
  HOME_FIXTURE_SCENARIOS,
  homeFixtureWorld,
  homeUrl,
  labMatrix,
  labUrl,
  LAB_DIRECTIONS,
  HOME_MODES,
  SCENARIO_IDS,
} from "./scenarios";
import { SECTION_LIMITS, HOME_TODAY_RANKING_VERSION } from "./derive";

const OUT = join(
  process.cwd(),
  "experience/home-operating-layer/fixtures/manifest.json",
);

export function buildManifest() {
  return {
    $comment:
      "Generated by src/lib/home-layer/fixtures/emit-manifest.ts. Do not hand-edit. Every number here is DERIVED from the fixture records; a diff in this file is a diff in what the review surfaces will say.",
    generator: "src/lib/home-layer/fixtures/emit-manifest.ts",
    rankingVersion: HOME_TODAY_RANKING_VERSION,
    clock: {
      today: HOME_FIXTURE_TODAY,
      asOfIso: HOME_FIXTURE_NOW_ISO,
      timeZone: HOME_FIXTURE_TIME_ZONE,
      locale: HOME_FIXTURE_LOCALE,
      dst: HOME_FIXTURE_DST,
    },
    story: {
      user: "Orla",
      planningPeriod: "The Orchard, 2026 season",
      activeProject: "Mara & Finn",
      projects: ["Mara & Finn", "Nora & Cian", "Aisling & Tom"],
    },
    sentinels: {
      bodyPrefix: NOTE_BODY_SENTINEL_PREFIX,
      extractPrefix: NOTE_EXTRACT_SENTINEL_PREFIX,
      noteCount: HOME_FIXTURE_NOTES.length,
      rule: "A scan that finds zero body sentinels in the population FAILS. It never reports clean.",
    },
    catalog: {
      totalProjects: HOME_FIXTURE_ALL_PROJECTS.length,
      orchardProjects: 4,
      mergedProjects: HOME_FIXTURE_ALL_PROJECTS.length - 4,
    },
    sectionLimits: SECTION_LIMITS,
    myWorkWindow: MY_WORK_WINDOW,
    myWorkReceipt: MY_WORK_COVERAGE_RECEIPT,
    analytics: {
      trendMinimumSnapshots: TREND_MINIMUM_SNAPSHOTS,
      maxExceptions: MAX_EXCEPTIONS,
      withheld: WITHHELD_CLAIMS.map((entry) => ({
        metric: entry.metric,
        defect: entry.defect,
      })),
    },
    snoozeCases: HOME_INBOX_SNOOZE_CASES.map((entry) => ({
      id: entry.id,
      fromIso: entry.fromIso,
      expectedResurfaceIso: entry.expectedResurfaceIso,
      adjustment: entry.adjustment,
    })),
    scenarios: SCENARIO_IDS.map((id) => {
      const world = homeFixtureWorld(id);
      const declared = HOME_FIXTURE_SCENARIOS.find((entry) => entry.id === id);
      const groups =
        world.myWork.kind === "ready"
          ? Object.fromEntries(
              Object.entries(world.myWork.groups).map(([name, rows]) => [
                name,
                rows.length,
              ]),
            )
          : null;
      return {
        id,
        label: declared?.label,
        proves: declared?.proves,
        actor: declared?.actor.name,
        seat: declared?.actor.seat,
        readScope: declared?.readScope,
        activeProjectId: declared?.activeProjectId,
        lensProjectId: declared?.lensProjectId,
        authorizedProjects: declared?.projects.length ?? 0,
        today: {
          asOfIso: world.today.asOfIso,
          sections: Object.fromEntries(
            Object.entries(world.today.sections).map(([name, rows]) => [
              name,
              rows.length,
            ]),
          ),
          accounting: world.today.accounting,
          quietAllowed: world.today.quiet.allowed,
          quietBlockedBy: world.today.quiet.blockedBy,
        },
        inbox: {
          rendered: world.badgeRendered,
          count: world.badge.count,
          coverage: world.badge.coverage,
          undetermined: world.badge.undeterminedCount,
          unreadableProjects: world.badge.unreadableProjectCount,
        },
        myWork: { kind: world.myWork.kind, groups },
        analytics: {
          claims: world.claims.map((claim) => ({
            metric: claim.metric,
            value: claim.value,
            status: claim.status,
            truthClass: claim.truthClass,
          })),
          exceptions: world.exceptions.length,
          ledgerRows: world.ledger.length,
          trend: world.trend.kind,
          lensOpens: world.lens.opens,
        },
        mustNeverRender: declared?.mustNeverRender,
        urls: {
          lab: Object.fromEntries(
            HOME_MODES.map((mode) => [mode, labUrl(LAB_DIRECTIONS[0], mode, id)]),
          ),
          home: Object.fromEntries(
            HOME_MODES.map((mode) => [mode, homeUrl(mode, id)]),
          ),
        },
      };
    }),
    captureMatrix: {
      directions: LAB_DIRECTIONS.length,
      modes: HOME_MODES.length,
      scenarios: SCENARIO_IDS.length,
      total: labMatrix().length,
    },
  };
}

export const MANIFEST_PATH = OUT;

/** The exact bytes the committed manifest must contain. */
export function serialiseManifest(): string {
  return `${JSON.stringify(buildManifest(), null, 2)}\n`;
}

function main(): void {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, serialiseManifest(), "utf8");
  console.log(`home-fixtures: wrote ${OUT}`);
}

// Only when run as a script. Importing this module must not write a file —
// `manifest.test.ts` imports it to compare against the committed bytes, and a
// check that rewrites the thing it is checking proves nothing.
const invokedDirectly = (process.argv[1] ?? "").includes("emit-manifest");
if (invokedDirectly) main();
