import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const [scratch,label,port] = process.argv.slice(2);
const resolution = createRequire('C:/Users/ethan/signal-studio-workspace/worktrees/app/feat-january-final-journeys/package.json');
const playwright = await import(pathToFileURL(resolution.resolve('@playwright/test')).href);
const { chromium, expect } = playwright.default || playwright;
const out = path.join(scratch,label), origin='http://127.0.0.1:'+port;
if(fs.existsSync(out))throw Error('Never overwrite capture');fs.mkdirSync(out);
const receipt={label,origin,adapter:'Actual components/controllers with local action/transfer ports; normal frozen CSS/fonts',cases:[],screenshots:[],errors:[],external:[]};
const browser=await chromium.launch({headless:true});
async function run(viewport,theme='light',short=false){
 const context=await browser.newContext({viewport,locale:'en-GB',timezoneId:'Europe/Dublin',colorScheme:theme,reducedMotion:'reduce'});
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!==origin){receipt.external.push(u.origin);return route.abort()}return route.continue()});
 const page=await context.newPage();let activeCase;
 page.on('console',message=>{if(['warning','error'].includes(message.type()))receipt.errors.push({case:activeCase,type:message.type(),text:message.text()})});
 page.on('pageerror',error=>receipt.errors.push({case:activeCase,type:'pageerror',text:String(error)}));
 page.on('response',r=>{if(r.status()>=400)receipt.errors.push({case:activeCase,type:'http',status:r.status(),url:r.url()})});
 const size=viewport.width+'-'+theme;
 async function visit(surface,state){await page.goto(origin+'/?surface='+surface+'&state='+state+'&theme='+theme);await page.locator('main').waitFor();if(surface==='connections'&&!['loading','member','flag-off','load-failed'].includes(state))await page.getByRole('heading',{name:'A home for this board’s files'}).waitFor();if(surface==='resources'&&!['list-loading','list-failed'].includes(state))await expect(page.getByText('Loading Resources…',{exact:true})).toHaveCount(0);}
 async function shot(name){await page.evaluate(()=>document.fonts.ready);const file=name+'-'+size+'.png';await page.screenshot({path:path.join(out,file),fullPage:true});const metrics=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,font:getComputedStyle(document.body).fontFamily,geist:document.fonts.check('14px Geist'),theme:document.documentElement.dataset.theme,background:getComputedStyle(document.body).backgroundColor,active:{tag:document.activeElement.tagName,text:document.activeElement.textContent?.slice(0,100),outline:getComputedStyle(document.activeElement).outlineStyle}}));receipt.screenshots.push({case:activeCase,file,metrics});if(metrics.scrollWidth>viewport.width+1)throw Error('Horizontal overflow '+metrics.scrollWidth);fs.writeFileSync(path.join(out,name+'-'+size+'.txt'),await page.locator('body').innerText());}
 async function test(name,fn){activeCase=name+'-'+size;const record={name,viewport,theme,ok:false};try{await fn(record);record.ok=true;}catch(error){record.failure=String(error);await page.screenshot({path:path.join(out,'failure-'+activeCase+'.png'),fullPage:true}).catch(()=>{});}record.calls=await page.evaluate(()=>window.__drive?.calls||[]).catch(()=>[]);receipt.cases.push(record);}
 async function checkCopy(record){const text=await page.locator('body').innerText();record.ownershipDisclosure=/owns? and can see|will own and be able to see/.test(text)&&/Drive space/.test(text);if(!record.ownershipDisclosure)throw Error('Ownership/visibility disclosure missing before consent/setup');}
 for(const state of short?['connected','access-gap']:['not-connected','connected-no-folder','connected','access-gap','reauth','setting-up','archived','member','flag-off','quota-warning','quota-critical','paid-quota','no-owner-choice','handover-attention','upload-blocks-handover'])await test('connections-'+state,async record=>{
  await visit('connections',state);
  if(['not-connected','connected-no-folder'].includes(state))await checkCopy(record);
  if(state==='reauth'){await expect(page.getByRole('button',{name:'Reconnect Google Drive'})).toBeVisible();await expect(page.getByText('Can edit',{exact:true})).toHaveCount(0);}
  if(state==='access-gap'){await expect(page.getByText('Access not confirmed',{exact:true})).toBeVisible();await expect(page.getByText('Can view',{exact:true})).toBeVisible();}
  if(state==='member'||state==='flag-off')await expect(page.getByRole('button',{name:/Connect Google Drive|Disconnect my Drive/})).toHaveCount(0);
  if(state==='archived')await expect(page.getByRole('button',{name:'Reconnect Google Drive'})).toBeDisabled();
  if(state==='quota-critical')await expect(page.getByText(/Storage is nearly full/)).toBeVisible();
  if(state==='quota-warning')await expect(page.getByText(/approaching your storage limit/)).toBeVisible();
  if(state==='paid-quota')await expect(page.getByText('50.0 MB per file',{exact:true})).toBeVisible();
  if(['no-owner-choice','handover-attention','upload-blocks-handover'].includes(state))await expect(page.getByRole('button',{name:/Review owner change|Confirm owner change|Continue saved change/})).toHaveCount(0);
  await shot('connections-'+state);
 });
 if(short){await context.close();return;}
 await test('loading-error-retry',async()=>{await visit('connections','loading');await expect(page.getByRole('status').filter({hasText:'Loading connection and Google access'})).toBeVisible();await shot('connections-loading');await page.evaluate(()=>window.__drive.releaseStatus());await page.getByRole('heading',{name:'A home for this board’s files'}).waitFor();await visit('connections','load-failed');await page.getByRole('button',{name:'Check again'}).waitFor();await shot('connections-load-failed');await page.evaluate(()=>window.__drive.statusFailure=false);await page.getByRole('button',{name:'Check again'}).click();await page.getByRole('heading',{name:'A home for this board’s files'}).waitFor();});
 await test('refresh-invalidates-access',async()=>{await visit('connections','connected');await expect(page.getByText('Can edit',{exact:true})).toBeVisible();await page.evaluate(()=>{window.__drive.status.access={state:'unavailable',checkedAt:null,people:[],otherPermissionCount:0}});await page.getByRole('button',{name:'Check again',exact:true}).click();await page.getByText(/No current permissions are confirmed here/).waitFor();await expect(page.getByText('Can edit',{exact:true})).toHaveCount(0);await shot('access-now-unavailable');});
 await test('disconnect-cancel-keyboard',async record=>{await visit('connections','connected');const trigger=page.getByRole('button',{name:'Disconnect my Drive'});await trigger.focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Keep connected'})).toBeFocused();await shot('disconnect-confirmation');await page.keyboard.press('Enter');await expect(trigger).toBeFocused();record.focusReturned=await trigger.evaluate(node=>node===document.activeElement);await expect(page.getByRole('group',{name:'Confirm Drive disconnect'})).toHaveCount(0);});
 await test('disconnect-pending-truth',async()=>{await visit('connections','disconnect-pending');await page.getByRole('button',{name:'Disconnect my Drive'}).click();await page.getByRole('button',{name:'Confirm disconnect'}).click();await page.getByText('Disconnect is not yet confirmed by Google. Check again before reconnecting.',{exact:true}).waitFor();await expect(page.getByText('Your Drive was disconnected.',{exact:true})).toHaveCount(0);await shot('disconnect-pending');});
 for(const state of ['connected','handover-pending'])await test('handover-'+state,async record=>{await visit('connections',state);if(state==='connected')await page.getByLabel('New storage owner').selectOption('target-maeve');const trigger=page.getByRole('button',{name:state==='connected'?'Review owner change':'Continue saved change'});await trigger.focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Go back'})).toBeFocused();await shot('handover-confirm-'+state);await page.keyboard.press('Enter');await expect(trigger).toBeFocused();record.focusReturned=await trigger.evaluate(node=>node===document.activeElement);await trigger.click();await page.getByRole('button',{name:'Confirm owner change'}).click();await page.getByText('Saved change: Maeve Synthetic Owner',{exact:true}).waitFor();await shot('handover-saved-'+state);});
 for(const state of ['list-loading','list-failed'])await test('resources-'+state,async()=>{await visit('resources',state);await expect(page.getByRole('button',{name:'Attach a file'})).toBeDisabled();await shot('resources-'+state);if(state==='list-loading')await page.evaluate(()=>window.__drive.releaseList());else{await page.evaluate(()=>window.__drive.listFailure=false);await page.getByRole('button',{name:'Try again'}).click();}await expect(page.getByRole('button',{name:'Attach a file'})).toBeEnabled();});
 for(const state of ['pending-owner','pending-other','pending-complete','pending-unavailable','pending-checking'])await test('resources-'+state,async record=>{
  await visit('resources',state);await expect(page.getByRole('button',{name:'Attach a file'})).toBeDisabled();await expect(page.getByRole('button',{name:/Remove Synthetic/})).toHaveCount(0);
  await page.locator('main > div').first().evaluate(()=>{});
  await page.locator('input[type=file]').evaluate(node=>{const data=new DataTransfer();data.items.add(new File(['synthetic'],'second.pdf',{type:'application/pdf'}));node.closest('div.relative').dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:data}));});
  await page.getByRole('button',{name:'Check for updates'}).focus();await page.keyboard.press('Enter');
  if(state==='pending-checking'){await expect(page.getByRole('button',{name:'Checking…'})).toBeDisabled();await shot('recovery-checking');await page.evaluate(()=>window.__drive.releaseRecovery());}
  if(state==='pending-complete'){await page.getByText('Stored in Google Drive · opens in a new tab',{exact:true}).waitFor();await expect(page.getByRole('button',{name:'Attach a file'})).toBeEnabled();await expect(page.getByRole('link',{name:/Synthetic supplier brief/})).toHaveAttribute('target','_blank');}
  else await expect(page.getByRole('button',{name:'Check for updates'})).toBeEnabled();
  record.intakeDispatches=await page.evaluate(()=>window.__drive.calls.filter(c=>c.name==='create'||c.name==='native').length);if(record.intakeDispatches!==0)throw Error('Pending drop dispatched new intake');
  if(state==='pending-other'&&(await page.evaluate(()=>window.__drive.calls.some(c=>c.name==='recover'))))throw Error('Other uploader probe dispatched');
  await shot('resources-'+state);
 });
 async function attach(){await page.getByLabel('Files to attach').setInputFiles({name:'synthetic.pdf',mimeType:'application/pdf',buffer:Buffer.alloc(1024,1)});}
 await test('upload-interruption-same-claim',async record=>{await visit('resources','upload');await attach();await page.getByText('50% received',{exact:true}).waitFor();await shot('upload-confirmed-progress');await page.getByRole('button',{name:'Stop sending'}).click();await page.getByRole('button',{name:'Retry same upload'}).waitFor();await expect(page.getByRole('button',{name:'Use Signal Studio'})).toHaveCount(0);await shot('upload-paused');await page.getByRole('button',{name:'Retry same upload'}).focus();await page.keyboard.press('Enter');await page.getByText('50% received',{exact:true}).waitFor();await page.evaluate(()=>window.__drive.releaseUpload());await page.getByText('Attached in Google Drive.',{exact:true}).waitFor();record.ids=await page.evaluate(()=>window.__drive.calls.filter(c=>c.name==='create').map(c=>c.args[1].resourceId));if(record.ids.length!==2||new Set(record.ids).size!==1)throw Error('Retry claim changed');await shot('upload-complete');});
 await test('upload-finalize-boundary',async()=>{await visit('resources','confirming');await attach();await page.getByText('50% received',{exact:true}).waitFor();await page.evaluate(()=>window.__drive.releaseUpload());await page.getByText('File received by Google. Confirming attachment…',{exact:true}).waitFor();await expect(page.getByText('Attached in Google Drive.',{exact:true})).toHaveCount(0);await shot('upload-confirming');await page.evaluate(()=>window.__drive.releaseFinalize());await page.getByText('Attached in Google Drive.',{exact:true}).waitFor();});
 await test('upload-lost-create',async()=>{await visit('resources','create-lost');await attach();await page.getByRole('button',{name:'Retry same upload'}).waitFor();await expect(page.getByRole('button',{name:'Use Signal Studio'})).toHaveCount(0);await shot('upload-create-uncertain');});
 for(const state of ['quota-full','fallback'])await test('native-'+state,async record=>{await visit('resources',state);await attach();await page.getByRole('button',{name:'Use Signal Studio'}).waitFor();if(state==='quota-full')await expect(page.getByText(/storage owner’s Drive is full/)).toBeVisible();record.nativeBeforeChoice=await page.evaluate(()=>window.__drive.calls.filter(c=>c.name==='native').length);if(record.nativeBeforeChoice!==0)throw Error('Implicit fallback');await shot('native-choice-'+state);if(state==='fallback')await page.evaluate(()=>window.__drive.nativeFailure=true);await page.getByRole('button',{name:'Use Signal Studio'}).click();await page.getByText(state==='fallback'?'Signal Studio could not confirm the upload. Refresh Resources before attaching this file again.':'Attached in Signal Studio.',{exact:true}).waitFor();await shot('native-result-'+state);});
 await test('flag-off-native-intake',async()=>{await visit('resources','flag-off');await attach();await page.getByRole('link',{name:/Synthetic supplier brief/}).waitFor();if(await page.evaluate(()=>window.__drive.calls.some(c=>c.name==='create')))throw Error('Flag-off Drive dispatch');await shot('flag-off-native');});
 await context.close();
}
try{
 for(const viewport of [{width:390,height:844},{width:1440,height:1000}])await run(viewport);
 for(const viewport of [{width:768,height:1024},{width:1920,height:1080}])await run(viewport,'light',true);
 for(const viewport of [{width:390,height:844},{width:1440,height:1000}])await run(viewport,'dark',true);
}finally{await browser.close();receipt.completedAt=new Date().toISOString();receipt.pass=receipt.cases.filter(c=>c.ok).length;receipt.fail=receipt.cases.length-receipt.pass;receipt.observations=receipt.cases.filter(c=>c.ownershipDisclosure===false||c.focusReturned===false).map(c=>({case:c.name,viewport:c.viewport,ownershipDisclosure:c.ownershipDisclosure,focusReturned:c.focusReturned}));fs.writeFileSync(path.join(out,'receipt.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({pass:receipt.pass,fail:receipt.fail,screenshots:receipt.screenshots.length,observations:receipt.observations,errors:receipt.errors.length,external:receipt.external.length}));process.exitCode=receipt.fail||receipt.external.length?1:0;}
